#!/bin/bash
#
# setup-bridge.sh - Configure transparent bridge between eth0 and eth1
#
# This script creates a Linux bridge (br0) that forwards all traffic
# between eth0 (switch/POS network) and eth1 (kitchen printer).
# The printer keeps its existing IP configuration unchanged.
#
# Usage: sudo ./setup-bridge.sh [--persist]
#   --persist: Make configuration permanent across reboots
#

set -euo pipefail

# Configuration
BRIDGE_NAME="br0"
ETH_SWITCH="eth0"     # Connected to switch/POS network
ETH_PRINTER="eth1"    # Connected to kitchen printer
PERSIST=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --persist)
            PERSIST=true
            shift
            ;;
        *)
            ;;
    esac
done

# Check root
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root" >&2
    exit 1
fi

# Check interfaces exist
for iface in "$ETH_SWITCH" "$ETH_PRINTER"; do
    if ! ip link show "$iface" &>/dev/null; then
        echo "Error: Interface $iface not found" >&2
        echo "Available interfaces:" >&2
        ip -br link show >&2
        exit 1
    fi
done

echo "Setting up bridge $BRIDGE_NAME between $ETH_SWITCH and $ETH_PRINTER..."

# Install bridge-utils if needed
if ! command -v brctl &>/dev/null; then
    echo "Installing bridge-utils..."
    apt-get update && apt-get install -y bridge-utils
fi

# Check if bridge already exists
if ip link show "$BRIDGE_NAME" &>/dev/null; then
    echo "Bridge $BRIDGE_NAME already exists"
    echo "Current state:"
    ip link show "$BRIDGE_NAME"
    bridge link show 2>/dev/null || brctl show "$BRIDGE_NAME"
    exit 0
fi

# Bring down interfaces
echo "Bringing down interfaces..."
ip link set "$ETH_SWITCH" down 2>/dev/null || true
ip link set "$ETH_PRINTER" down 2>/dev/null || true

# Remove any existing IP addresses
ip addr flush dev "$ETH_SWITCH" 2>/dev/null || true
ip addr flush dev "$ETH_PRINTER" 2>/dev/null || true

# Create bridge
echo "Creating bridge..."
ip link add name "$BRIDGE_NAME" type bridge

# Set bridge options for transparent forwarding
echo "Configuring bridge options..."
# Disable STP (Spanning Tree Protocol) for simple point-to-point
ip link set "$BRIDGE_NAME" type bridge stp_state 0
# Set forward delay to 0 for immediate forwarding
ip link set "$BRIDGE_NAME" type bridge forward_delay 0
# Set ageing time (300 seconds default)
ip link set "$BRIDGE_NAME" type bridge ageing_time 30000

# Add interfaces to bridge
echo "Adding interfaces to bridge..."
ip link set "$ETH_SWITCH" master "$BRIDGE_NAME"
ip link set "$ETH_PRINTER" master "$BRIDGE_NAME"

# Bring everything up
echo "Bringing up interfaces..."
ip link set "$ETH_SWITCH" up
ip link set "$ETH_PRINTER" up
ip link set "$BRIDGE_NAME" up

# Set promiscuous mode for interfaces (required for bridge)
ip link set "$ETH_SWITCH" promisc on
ip link set "$ETH_PRINTER" promisc on

# Enable IP forwarding (safety measure)
echo "Enabling IP forwarding..."
sysctl -w net.ipv4.ip_forward=1 >/dev/null

# Disable netfilter on bridge (let traffic pass unfiltered)
echo "Configuring sysctl for bridge..."
sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true
sysctl -w net.bridge.bridge-nf-call-arptables=0 >/dev/null 2>&1 || true

# Persist configuration if requested
if $PERSIST; then
    echo "Making configuration persistent..."

    # Create network interfaces configuration
    cat > /etc/network/interfaces.d/kitchen-printer-tap <<EOF
# Kitchen Printer Tap bridge configuration
# Generated by setup-bridge.sh on $(date)

auto $BRIDGE_NAME
iface $BRIDGE_NAME inet manual
    bridge_ports $ETH_SWITCH $ETH_PRINTER
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0
    up ip link set $ETH_SWITCH promisc on
    up ip link set $ETH_PRINTER promisc on
EOF

    # Add sysctl persistence
    cat > /etc/sysctl.d/99-kitchen-printer-tap.conf <<EOF
# Kitchen Printer Tap sysctl settings
# Generated by setup-bridge.sh on $(date)

net.ipv4.ip_forward=1
net.bridge.bridge-nf-call-iptables=0
net.bridge.bridge-nf-call-ip6tables=0
net.bridge.bridge-nf-call-arptables=0
EOF

    echo "Persistent configuration saved."
    echo "  - /etc/network/interfaces.d/kitchen-printer-tap"
    echo "  - /etc/sysctl.d/99-kitchen-printer-tap.conf"
fi

# Verify setup
echo ""
echo "Bridge setup complete!"
echo ""
echo "Bridge status:"
ip link show "$BRIDGE_NAME"
echo ""
echo "Bridge ports:"
bridge link show 2>/dev/null || brctl show "$BRIDGE_NAME"
echo ""
echo "To verify traffic forwarding, run:"
echo "  tcpdump -i $BRIDGE_NAME -n port 9100"
echo ""
echo "To rollback this configuration, run:"
echo "  sudo ./rollback-bridge.sh"
